sudo apt install bat
sudo apt install lsd
sudo apt install ripgrep
sudo apt install zoxide
sudo apt install fd
sudo apt install tmux
sudo apt install jq
sudo apt install stow
sudo apt install fzf
sudo apt install numbat
sudo apt install hyperfine
